### ISSUE TITLE
source_validator fails keyring check for timezone

### ISSUE THREAD

**Issue by danyspin97** [openSUSE/obs-service-source_validator#110]
With the changes introduced in 27a0a969915016b5d7d3a9f18495d743e353dcc7, source_validator fails when it finds more than one `.keyring` file. However, timezone has `timezone.keyring` and `timezone-java.keyring` and thus fail.

**Comment by dirkmueller** [comment]
yes, that is an intentional failure. I have fixed all failing packages in Factory for this change. especially for timezone please pick the factory changes rather than maintaining an off-package for old dists. we already had to merge it with factory again twice in its history: https://build.opensuse.org/package/rdiff/openSUSE:Factory/timezone?linkrev=base&rev=141

**Comment by danyspin97** [comment]
I see. Please open a bug next time so that I am aware of this change and I can fix it in SLE.
